### ISSUE TITLE
CK crashing when toggling back

### ISSUE THREAD

**Issue by wooloogooloo** [narcode/codeklavier-extensions#4]
HI CK MASTER!

I get this when i try to toggle back to motippets after hello world

Exception in thread ck loop thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Anne/codeklavier/hybrid/hybrid.py", line 345, in ck_loop
    ck_deltatime += deltatime
TypeError: unsupported operand type(s) for +=: 'dict' and 'float'

**Comment by narcode** [comment]
@wooloogooloo  could you please bring this bug to the codeklavier repository and close it... it doesnt belong here... 
Also the latest ck_dev branch added the shortcuts thing for the extensions. Please test and let me know. And it is only done for motifs (not mini ones)

**Comment by wooloogooloo** [comment]
this is the crash i get Traceback (most recent call last):
  File "codeklavier.py", line 156, in <module>
    boot(configfile=config, version=play)
  File "codeklavier.py", line 103, in boot
    eval(version.main())
  File "/Users/Anne/codeklavier/hybrid/hybrid.py", line 152, in main
    mainMem.parse_midi(msg, 'full', ck_deltadif['all'], ck_deltadif['low'], ck_deltadif['hi'], ck_deltadif['mid'])
  File "/Users/Anne/codeklavier/CodeKlavier/motippets_classes.py", line 388, in parse_midi
    self.mapscheme.snippets(motif)
  File "/Users/Anne/codeklavier/CodeKlavier/Mapping.py", line 246, in snippets
    self.__keyboard.type(snippet)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynput/keyboard/_base.py", line 447, in type
    for i, character in enumerate(string):
TypeError: 'NoneType' object is not iterable

**Comment by narcode** [comment]
@wooloogooloo fixed in latest ck_dev branch. Test, enjoy, milk.
